### ISSUE TITLE
Log Macro expansion doesn't work properly

### ISSUE THREAD

**Issue by dpravn** [KjellKod/g3log#215] opened 2017-07-19 15:02 UTC
I have code similar to the snippet given below.  If expression1 is false we expect expression2 should get executed but it doesn't run as per this logic.  If the if condition has {} then it works fine.  Its something to do with if condition in the macro definition. 

	if (expression1)
		LOG(WARNING) << "Failed to Create";
	else
		expression2;

Also can you please let me know how to set locale for logging stream?

**Comment by KjellKod** [comment] 2017-07-19 15:32
Not sure what the problem is for the first issue. Are you sure this is `LOG` and not `LOG_IF`?
I tested the following
```
   void foo(int first, int second)
   {
       if (first != second)
          LOG(WARNING) << "A: First not equal to second";
       else
         LOG(INFO) << "A: First was equal to second";

       if (first != second) {
          LOG(WARNING) << "B: First not equal to second";
       } else {
         LOG(INFO) << "B: First was equal to second";
      }
```
The output was:
```
2017/07/19 09:30:05 953692      WARNING [main.cpp->foo:30]      A: First not equal to second
2017/07/19 09:30:05 953697      WARNING [main.cpp->fooo:35]      B: First not equal to second
```

**Comment by KjellKod** [comment] 2017-07-19 15:44
Hi 
That's a correct observation. Unfortunately that comes with the option of turning on-off levels
I.e. in `g3log.hpp`
```
#define LOG(level) if(g3::logLevel(level)) INTERNAL_LOG_MESSAGE(level).stream()
```
The problem is that there is no way for the macro to add its own `{}` parenthesis. 

If you are not interested in turning on/off levels then my suggestion would be to fork the repo and just remove that from the `LOG` macros. 

Just as a FYI: All C++ guidelines and company standards that I have seen recommend to always use `braces`. If you use g++ you should (depending on warning level) also see in this case a compiler warning that there might be an issue in the code
```
add explicit braces to avoid dangling else [-Wdangling-else]
```

**Comment by KjellKod** [comment] 2017-07-19 15:47
Currently there is no support for internationalization in g3log.   There is a pull request that addresses that but that very pull request is blocked for documentation and local examples that are missing.  Please see https://github.com/KjellKod/g3log/pull/191 if you are interested in this feature. 

I'm assuming that setting the locale is not logger specific but a c++ (optionally also platfrom) specific question so google is your friend here.

**Comment by KjellKod** [comment] 2017-07-19 15:48
Thanks for using g3log and thanks for providing a great question. 

Feel free to continue this thread if you have additional questions. I will close it however as I see no action on my part at this point.

**Closed by KjellKod** 2017-07-19 15:48 UTC
Labels: question, wontfix

**Comment by dpravn** [comment] 2017-07-20 13:33
Hi KjellKod,

Thanks for your efforts in building this library and responding to our queries quickly.  The main reason I asked for setting of locale is to avoid comma separated numbers in log files. It would be great if it can be disabled some how.

Thanks 
Praveen

**Comment by KjellKod** [comment] 2017-07-20 13:50
My suggestion is that you create your own logging sink. A good start if you are on Linux is to look at the g3sinks repo.

See also the documentation for G3log, the API doc. By having a sink that revive the LogMessage struct instead of a std::string you will be given full power of formatting
