### ISSUE TITLE
Program crashed when worker not define in local 

### ISSUE THREAD

**Issue by cztchoice** [KjellKod/g3log#89] opened 2016-04-21 14:37 UTC
When I run the following code
```c++
#include "g3log/logworker.hpp"

std::unique_ptr<g3::LogWorker> worker;

int main(int argc, const char * argv[]) {
    worker = g3::LogWorker::createLogWorker();
    return 0;
}
```
the program crash when exit(after return 0). Is this acceptable?
Besides, if I put the define of worker in main. No crash.
Thanks.

I've test in VS2013 and Xcode. Both crashed.
the xcode message
```
LOGGER NOT INITIALIZED:
		Hello
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
```
stack trace:
```
#0	0x00007fff95f55f06 in __pthread_kill ()
#1	0x00000001000a842d in pthread_kill ()
#2	0x00007fff8a8446e7 in abort ()
#3	0x00007fff86c14f81 in abort_message ()
#4	0x00007fff86c3aa2f in default_terminate_handler() ()
#5	0x00007fff9457e6c3 in _objc_terminate() ()
#6	0x00007fff86c3819e in std::__terminate(void (*)()) ()
#7	0x00007fff86c38213 in std::terminate() ()
#8	0x0000000100001d6f in __clang_call_terminate ()
#9	0x000000010000fbb8 in g3::LogWorker::~LogWorker() ()
#10	0x0000000100001c83 in std::__1::default_delete<g3::LogWorker>::operator()(g3::LogWorker*) const [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2516
#11	0x0000000100001c68 in std::__1::unique_ptr<g3::LogWorker, std::__1::default_delete<g3::LogWorker> >::reset(g3::LogWorker*) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2715
#12	0x0000000100001c0b in std::__1::unique_ptr<g3::LogWorker, std::__1::default_delete<g3::LogWorker> >::~unique_ptr() [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2683
#13	0x0000000100001bfb in std::__1::unique_ptr<g3::LogWorker, std::__1::default_delete<g3::LogWorker> >::~unique_ptr() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2683
#14	0x00007fff8a84546b in __cxa_finalize_ranges ()
#15	0x00007fff8a84576f in exit ()
#16	0x00007fff8f4315b4 in start ()
#17	0x00007fff8f4315ad in start ()
```

**Comment by KjellKod** [comment] 2016-04-21 16:56
What are you trying to achieve here? It seems weird and counter intuitive to put a unique_ptr in static global space.


Put it inside the main and you should be good. When main exits the unique ptr falls out of scope and cleanup and destruction happens just like it should

**Comment by KjellKod** [comment] 2016-04-21 16:58
Also. The code and the error message you posted are not correlated. There's no "HELLO" log input so obviously you are doing something else

**Comment by cztchoice** [comment] 2016-04-21 23:59
Sorry for put the wrong message( I remove the Hello log the make code simple enough), real message is this (Just without Hello log)
```
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
```
What I want to know is how and why G3log cause this? I try other type of unique_ptr, they didn't show any error message, just run and exit.
Thanks.

**Comment by KjellKod** [comment] 2016-04-22 00:44
I think it is a bug in the runtime environment you are in. I've seen similar things before when threaded constructs are put in static space

**Comment by KjellKod** [comment] 2016-04-22 00:45
Have you tried with a shared_ptr instead? This seems suspiciously similar to https://github.com/KjellKod/g3log/issues/61#issuecomment-159312647

**Comment by cztchoice** [comment] 2016-04-22 05:58
i use unique_ptr because creatLogWorker return type is unique_ptr and LogWorker's constructor is private, I don't know how to use shared_ptr here, any ideas?

I don't think it is a runtime bug,because Vs2013 and xcode(use clang) all have the same result. I do think there is something in g3log code conflict with the c++ destory step. But I don't know where.

Thanks.

**Comment by KjellKod** [comment] 2016-04-22 06:04
1) it's easy to move the internal pointer in a unique_ptr to a shared_ptr. Ref: "release"

2) I will try to reproduce this.
In the meantime. Could you please explain why you want to store a unique_ptr in static storage? 

The normal use of g3log is to store the logworker inside the main function. When that function goes out of scope the logger is destroyed in a clean way. 

Static destruction is a whole other issue altogether

**Comment by cztchoice** [comment] 2016-04-22 06:05
The error occures when calling ShutdownLogging and lock g_logging_init_mutex which is a local variable in g3log.cpp in anonymous namespace, along with a g_log_instanse, i think this could happen when the destory of mutex called before logworker instanse, am I right?

**Comment by KjellKod** [comment] 2016-04-22 06:10
FYI: I do not consider this a g3log issue but an unfortunate programming practice that should be avoided

See this discussion for some hints http://stackoverflow.com/questions/21157476/why-global-or-static-object-can-lead-to-crash-when-program-exit

**Comment by KjellKod** [comment] 2016-04-22 06:22
See my link above. I believe it's due to destruction order in static storage (likely what you just pointed out). 

G3log is not meant to be saved in static storage.

What are you trying to achieve by storing a unique_ptr in static global space? If you explain the use case I can see if it is something I can help you out with.

I do not plan to create a "fix" for use cases like the one you are describing (since it's bad practice to use complex constructs in static storage) but I might be able to help out if you explain the need.

**Comment by cztchoice** [comment] 2016-04-22 13:46
My case:
In my project, I want to store Log relate function and variable in a file named logger.cpp, and call it with function InitializeLogger(Dir) via logger.h.
And other files shouldn't know how i Initialize Logger, and use the Logger worker, They just call LOG(INFO) etc.
How can I achieve this?
Thanks for your patience

**Comment by KjellKod** [comment] 2016-04-22 16:10
Initialize the logger in your main function (see examples directory).

When you need to call LOG then all that is needed is to include the g3log in the file where you do the log call

#include <g3log/g3log.h>

Please see the example directory

**Comment by KjellKod** [comment] 2016-04-22 16:11
The code got removed the include should be for g3log/g3log.h

**Comment by cztchoice** [comment] 2016-04-23 00:34
> FYI: I do not consider this a g3log issue but an unfortunate programming practice that should be avoided
I think this is g3log issue because g3log use static variable in https://github.com/KjellKod/g3log/blob/master/src/g3log.cpp#L3
This usage make declaring worker global impossible. (bad practice, too? One bad practice shouldn't cause error)
Also, As a library, I think g3log shouldn't imply people use it using strict order or place.

Thanks.

**Comment by KjellKod** [comment] 2016-04-23 01:29
That's OK. Everyone is entitled to its own opinion. 

The use cases and recommended use cases for g3log is well documented. If you need to have it global you can do that but you have to destroy the worker before the program exits. I showed you have to do that in the link to another issue.

**Closed by KjellKod** 2016-04-23 01:29 UTC

**Comment by Mahendrakumar1985** [comment] 2019-03-07 16:49
Hello,

As discussed over your blog "https://kjellkod.wordpress.com/2014/08/16/presenting-g3log-the-next-version-of-the-next-generation-of-loggers" regarding crashing of g3log when appending the code into my dll, here are my comments.

2. You never call the top I initialization only the bottom one. Once it goes out of scope the logger is deleted and get shutdown automatically.
>> you can see the commented code which was previously written in the method itself however i got a crash.

3. The way to stop the logger is through RAII not like this. Please read the docs in the repo.
>> I thought writing worker.reset() will dispose the worker but that also didn't work and gave me crash. I tried to omit that line however no luck. I tried to visit all your code but nothing found helpful to me. Well , i am new to cpp and i will appreciate if you can help me mentioning line of code.

4. Your log output isn’t complete.
>> but as per writing LOG(info), it has perfectly written the lines in my log file. Afterwards , i feel that something is crashing.

Please help me to come out of this situation as I am unaware of cpp coding and trying to integrate in the code given to me.

Thanks in advance

**Comment by KjellKod** [comment] 2019-03-07 16:52
@Mahendrakumar1985 Please open up a new ticket and start from scratch. Do not hijack this closed ticket as it is closed. 

Describe your steps from the beginning, don't assume the community will go to the blog to read about the ticket description. Please do not mix in commented out code but the actual code that is used. 

The reason for this is that people should be able to search through old tickets and find their solution. That's not possible if your ticket description is on a blog somewhere.
