### ISSUE TITLE
Crash during log rotation

### ISSUE THREAD

**Issue by dave-n** [KjellKod/g3log#222] opened 2017-08-22 15:08 UTC
## Overview
I seem to be experiencing a crash during log rotation. The problem could be my code, but I don't see the issue:
## Environment
```
$ uname -a
Linux localhost.localdomain 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


```
## Steps to reproduce
Run the program twice

## Crash when the log is rotated
```
$ ./g3log_explore 
g3log_explore

Exiting, log location: log_dir/g3log_explore.log
$ ./g3log_explore 
g3log_explore
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
2017/08/22 10:01:46 646584

***** FATAL SIGNAL RECEIVED ******* 
Received fatal signal: SIGABRT(6)       PID: 12818

***** SIGNAL SIGABRT(6)

******* STACKDUMP *******
        stack dump [1]  /usr/local/lib/libg3logger.so.1.3.2-27+0x553c0 [0x7f5fa36903c0]
        stack dump [2]  /lib64/libc.so.6+0x35250 [0x7f5fa2871250]
        stack dump [3]  /lib64/libc.so.6gsignal+0x37 [0x7f5fa28711d7]
        stack dump [4]  /lib64/libc.so.6abort+0x148 [0x7f5fa28728c8]

        stack dump [5]  /lib64/libstdc++.so.6 : __gnu_cxx::__verbose_terminate_handler()+0x165 [0x7f5fa31759d5]
        stack dump [6]  /lib64/libstdc++.so.6+0x5e946 [0x7f5fa3173946]
        stack dump [7]  /lib64/libstdc++.so.6+0x5e973 [0x7f5fa3173973]
        stack dump [8]  /lib64/libstdc++.so.6+0xb52c5 [0x7f5fa31ca2c5]
        stack dump [9]  /lib64/libpthread.so.0+0x7dc5 [0x7f5fa241fdc5]
        stack dump [10]  /lib64/libc.so.6clone+0x6d [0x7f5fa293376d]

Exiting after fatal event  (FATAL_SIGNAL). Fatal type:  SIGABRT
Log content flushed sucessfully to sink


LOGGER NOT INITIALIZED:
                sleep(2) took: 2000941399 nanoseconds


```
### g3log_explore.cpp
```
#include <iostream>
#include <thread>
#include <sstream>
#include <unistd.h>
#include <g3log/g3log.hpp>
#include <g3log/logworker.hpp>
#include <g3sinks/LogRotate.h>
#include <g3log/std2_make_unique.hpp>

#include "Stopwatch.hpp"


void thread_func(int my_tid)
{
    static const unsigned int num_logs_per_thread = 10;
    LOG(INFO) << "Launching thread " << my_tid;
    for (unsigned int i = 0; i < num_logs_per_thread; ++i) {
        LOG(INFO) << "Log msg " << i << " from thread " << my_tid;
        usleep(10); // 10 micro * rand? would that add anything
    }

    LOG(INFO) << "Finishing thread " << my_tid;
}


int main(int argc, char* argv[])
{
    int ret_val = 0;
    std::cout << "g3log_explore" << std::endl;

    using namespace g3;

    std::unique_ptr<LogWorker> logworker{ LogWorker::createLogWorker() };

    auto sinkHandle = logworker->addSink(std2::make_unique<LogRotate>("g3log_explore", "log_dir"),
                                         &LogRotate::save);

    // initialize the logger before it can receive LOG calls
    initializeLogging(logworker.get());
    // You can call in a thread safe manner public functions on the logrotate sink
    // The call is asynchronously executed on your custom sink.
    const int k10MBInBytes = 10 * 1024 * 1024;
    std::future<void> received = sinkHandle->call(&LogRotate::setMaxLogSize, k10MBInBytes);

    // Run the main part of the application. This can be anything of course, in this example
    // we'll call it "RunApplication". Once this call exits we are in shutdown mode

    for (auto i = 0; i < 50; ++i) {
        LOG(INFO)  << "Info Logging message " << ++i;
        LOG(WARNING) << "Warning Logging message " << ++i;
        LOG(DEBUG) << "Logging message " << i;
    }

    static const int num_threads = 15;
    std::thread t[num_threads];

    LOG(INFO) << "Launching " << num_threads << " threads from main" << std::endl;
    //Launch a group of threads
    for (int i = 0; i < num_threads; ++i) {
        t[i] = std::thread(thread_func, i);
    }

    for (int i = 0; i < num_threads; ++i) {
        t[i].join();
    }

 
    std::ostringstream ss;
    Stopwatch::describe(ss);
    LOG(INFO) << ss.str();

    Stopwatch timer;
    timer.reset();
    for (unsigned int i = 0; i < 1e5; i++) {
        LOG(INFO) << "Logging";
    }
    LOG(INFO) << "100,000 log messages took " << timer.elapsed() << " nanoseconds";
    LOG(INFO) << "Average " << (timer.elapsed() / 1e5) << "ns";

    timer.reset();
    auto delta =  timer.elapsed();
    LOG(INFO) << "Successive calls to now took " << delta << " nanoseconds";

    timer.reset();
    usleep(2000);
    auto sleepTime = timer.elapsed();

    LOG(INFO) << "usleep(2000) took: " << sleepTime << " nanoseconds";
    LOG(INFO) << "usleep(2000) took: " << sleepTime / 1e3 << " microseconds";
    LOG(INFO) << "usleep(2000) took: " << sleepTime / 1e6  << " milliseconds";
    LOG(INFO) << "usleep(2000) took: " << sleepTime / 1e9  << " seconds";

    timer.reset();
    sleep(2);
    sleepTime = timer.elapsed();
    LOG(INFO) << "sleep(2) took: " << sleepTime << " nanoseconds";
    LOG(INFO) << "sleep(2) took: " << sleepTime / 1e3 << " microseconds";
    LOG(INFO) << "sleep(2) took: " << sleepTime / 1e6 << " milliseconds";
    LOG(INFO) << "sleep(2) took: " << sleepTime / 1e9 << " seconds";
    return ret_val;
}

```
### Stopwatch.hpp
```
#pragma once

#include <chrono>
#include <iostream>


template <class resolution> class Stopwatch_res
{
    std::chrono::time_point<std::chrono::steady_clock> stopped_;
    std::chrono::time_point<std::chrono::steady_clock> started_;

public:
    Stopwatch_res()
    {
        reset();
    }
    void reset()
    {
        started_ = std::chrono::steady_clock::now();
        stopped_ = started_;
    }
    void stop()
    {
        stopped_ = std::chrono::steady_clock::now();
    }
    std::chrono::time_point<std::chrono::steady_clock> now()
    {
        return std::chrono::steady_clock::now();
    }
    int64_t elapsed(bool stop_now)
    {
        if (stop_now) {
            stop();
        }
        return std::chrono::duration_cast<resolution>(stopped_ - started_).count();
    }

    int64_t elapsed()
    {
        return elapsed(true);
    }

    static void describe(std::ostream& out)
    {
        out << "High Resolution Clock has " <<  std::chrono::high_resolution_clock::period::den << " ticks per second" << std::endl;
        auto freq = 1.0 / std::chrono::high_resolution_clock::period::den;
        out << "High Resolution Clock Frequency " << freq << std::endl;
        out << "Steady Clock has " <<  std::chrono::steady_clock::period::den << " ticks per second" << std::endl;
        freq = 1.0 / std::chrono::steady_clock::period::den;
        out << "Steady Clock Frequency " << freq << std::endl;
        out << "This implementation uses std::chrono::steady_clock" << std::endl;
    }
    static const std::string& units();
    static double freq();
};

// Template specialization for slightly easier use by clients
typedef Stopwatch_res<std::chrono::nanoseconds> Stopwatch_ns;
typedef Stopwatch_res<std::chrono::microseconds> Stopwatch_us;
typedef Stopwatch_res<std::chrono::milliseconds> Stopwatch_ms;
typedef Stopwatch_res<std::chrono::seconds> Stopwatch_s;
// default to the highest resolution
typedef Stopwatch_res<std::chrono::nanoseconds> Stopwatch;
// unit string for logging
template<> const std::string& Stopwatch_ns::units()
{
    static std::string unit_string(" ns");
    return unit_string;
}
template<> const std::string& Stopwatch_us::units()
{
    static std::string unit_string(" µs");
    return unit_string;
}
template<> const std::string& Stopwatch_ms::units()
{
    static std::string unit_string(" ms");
    return unit_string;
}
template<> const std::string& Stopwatch_s::units()
{
    static std::string unit_string(" s");
    return unit_string;
}
// Return frequency to scale to seconds
template<> double Stopwatch_ns::freq()
{
    return double(1.0)/1e9;
}
template<> double Stopwatch_us::freq()
{
    return double(1.0)/1e6;
}
template<> double Stopwatch_ms::freq()
{
    return double(1.0)/1e3;
}
template<> double Stopwatch_s::freq()
{
    return 1;
}

```

**Comment by KjellKod** [comment] 2017-09-24 02:04
I have been unable to reproduce the issue.  I put up a test repository with your code snippet on a branch named after this issue. https://github.com/KjellKod/g3log_examples/tree/issue_222
Please try it again. I am suspecting that the code snippet as given does not trigger the error you reported.

**Comment by KjellKod** [comment] 2017-09-24 02:15
@dave-n here's a thought. Maybe it's the regex itself that does not work on your platform?
I have not tried the gcc version you had. On my current laptop it is using gcc 5.4.1. 
You can verify this by running some simple regex examples 
One option could be for you to use boost_regex or fix the compiler version (or compile option? to enable regex)

**Comment by KjellKod** [comment] 2017-09-27 03:15
I am closing this issue since the issue is with a specific compiler version for g3sinks - another repo. https://github.com/KjellKod/g3sinks

**Closed by KjellKod** 2017-09-27 03:15 UTC
Labels: invalid, question
