### ISSUE TITLE
LogWorker dtor sync issue

### ISSUE THREAD

**Issue by OfekShilon** [KjellKod/g3log#111] opened 2016-08-17 09:50 UTC
In ~LogWorker(), the lines:
       auto bg_clear_sink_call = [this] { _impl._sinks.clear(); };
       auto token_cleared = g3::spawn_task(bg_clear_sink_call, _impl._bg.get());
       token_cleared.wait();

can cause a hang in managed/native mixed executables. I had to revert to the simple -
       _impl._sinks.clear();

My analysis is as follows:  this dtor can be reached after say Application.Shutdown is called, and since [all native threads are considered background threads](https://msdn.microsoft.com/en-us/library/h339syd0%28v=vs.110%29.aspx) they are just unceremoniously terminated. At this point there's no way of spawning a native task, and the application just hangs indefinitely.

Seems the less-hackish (but still not completely safe) thing to do would be to detect whether the worker thread is still alive before spawning a bg_clear_sink_call task.   There's certainly no point in calling it when there's no worker queue to clear.

**Comment by KjellKod** [comment] 2016-08-17 14:39
Hi please take a look at: https://github.com/KjellKod/g3log/issues/91 and https://github.com/KjellKod/g3log/issues/88#issuecomment-219030139. 

Let me know if this resolves your issue

**Comment by KjellKod** [comment] 2016-08-17 14:40
I'll try to remember to add this to the documentation.

**Comment by OfekShilon** [comment] 2016-08-17 15:46
Not sure I understand.  How do I call anything like g_logger.reset()?   LogWorker currently has no reset() method, and g_logger_instance is inaccessible externally.

**Comment by KjellKod** [comment] 2016-08-17 16:20
Did you see the code example at:
https://github.com/KjellKod/g3log/issues/88#issuecomment-219030139

*Contact Information*
*Kjell Hedström*
*Mobile:  +1 - 617.378.1915*

*E-mail: Hedstrom@KjellKod.cc*

**Comment by OfekShilon** [comment] 2016-08-17 17:03
Thanks! That helps.  I also had to move around the logger to get it to be created early on the main thread, *and* use legacy debugging engine to completely avoid the hang. Turns out the VS2015 default debugging engine [doesn't handle mixed code very well](http://stackoverflow.com/questions/38337655/visual-studio-2015-mixed-c-c-debugger-extremely-slow-to-start#comment64092356_38337655).

**Comment by KjellKod** [comment] 2016-08-17 18:00
If you have suggestions how to improve the documentation to help windows
users please add them here or in a pull request :)

ref: https://github.com/KjellKod/g3log/blob/master/API.markdown

**Comment by OfekShilon** [comment] 2016-08-31 14:17
Turns out the hang issue still persists, and I had to revert to the synchronous _impl._sinks.clear(); .

Since the original code invokes the same call asynchronously _and then waits on it_ (and since async invocation fails during mixed managed/native application shutdown) I see no reason to leave it asynchronous.  Suggest putting the simple synchronous call at the trunk.

**Comment by KjellKod** [comment] 2016-08-31 15:52
Can you provide a simple test application that shows this behavior?  I believe what you say it's just that since it seems to work for the people that opened https://github.com/KjellKod/g3log/issues/91 and https://github.com/KjellKod/g3log/issues/88#issuecomment-219030139.  I would need to understand better what the differences are.  

It's possible that it's the mix of native/managed code so a tiny hello-world example that shows this would be highly useful.

**Comment by KjellKod** [comment] 2016-09-25 03:15
@OfekShilon any example code that you could provide here? Otherwise I will close it

**Comment by OfekShilon** [comment] 2016-09-25 05:36
Sorry, I will try to find time to put something together.

On Sep 25, 2016 6:15 AM, "Kjell Hedström" <notifications@github.com> wrote:

@OfekShilon <https://github.com/OfekShilon> any example code that you could
provide here? Otherwise I will close it

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/KjellKod/g3log/issues/111#issuecomment-249400074>, or mute
the thread

**Comment by KjellKod** [comment] 2016-12-12 20:26
Closed due to inactivity and I have yet to reproduce this myself.

**Closed by KjellKod** 2016-12-12 20:26 UTC
Labels: question
