### ISSUE TITLE
g3log 1.3.1 now requires git to compile

### ISSUE THREAD

**Issue by morph208** [KjellKod/g3log#251] opened 2018-03-09 09:43 UTC
Hey,

First of all, thanks for all your hard work. g3log is  a very cool piece of software.

**Context:** We are using g3log 1.3 for a while now. We had to upgrade to g3log 1.3.1 because we updated our CMake to 3.10 and the previous version did not work (a problem where g3log wrongly detected that our CMake was less than 3.4 even though it was 3.10). 

**Issue:** The problem is that you now added a dependency to git to compile. Indeed you are using a call to git to retrieve the version. As far as I see, it's merely to display the version in CMake. I think it's wrong to rely on git to be in the path to be able to compile g3log. You cannot assume that git will be in the path. I might have downloaded the zip archive. Or I might have clone the project via a GUI (such as GitKraken) that ships with its own git implementation inside. In both cases I don't have git and it should not prevent me to compile.

**Actual error:** 

`git : The term 'git' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 

spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:2

+ (git rev-list --branches HEAD | Measure-Object -line).Lines
+  ~~~

    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException

    + FullyQualifiedErrorId : CommandNotFoundException

CMake Error at CMakeLists.txt:88 (math):
  math cannot parse the expression: "/255": syntax error, unexpected
  exp_DIVIDE, expecting exp_PLUS or exp_MINUS or exp_OPENPARENT or exp_NUMBER
  (1)

CMake Error at CMakeLists.txt:89 (math):
  math cannot parse the expression: "%255": syntax error, unexpected exp_MOD,
  expecting exp_PLUS or exp_MINUS or exp_OPENPARENT or exp_NUMBER (1)

git build version: 
version base: 
version remainder: 
Software Version: 1.3.-`

**Comment by KjellKod** [comment] 2018-03-09 13:45
I’m marking this as a feature request. A possible way to adress it is to pass in a version number in the CMake arguments. If that version number is defined then the version number calculation can be skipped.

G3log is built currently with CMake and it’s hosted with git. When building it it relies on CMake and git tools. That’s by design.

It’s possible to make your own build makefile structure, remove the problem code, or address it as suggested above and put up a pull request for the community 

G3log is public domain software. Unless it’s a critical bug I will rely on the community to address fringe feature requests .

 I.e the fastest way to adress this is to adress it yourself and out IPL a pull request

**Closed** 2018-03-26 03:57 UTC
Labels: wontfix
