### ISSUE TITLE
Missing import lib on windows dll

### ISSUE THREAD

**Issue by pendenaor** [KjellKod/g3log#13] opened 2015-06-17 07:29 UTC
Hi,

When compiling the VC2013 solution, there's no g3logger_shared.lib generated.

Looking into the solution, i see no definition file or /EXPORT compiler flag or __declspec(export) into g2log.hpp, so VC2013 does not generate import lib (see https://msdn.microsoft.com/en-us/library/67wc07b9.aspx for more information).

**Comment by KjellKod** [comment] 2015-06-17 10:21
Thanks 
I will look into it. According to the Cmake file it should be generated so something is amiss https://github.com/KjellKod/g3log/blob/master/Build.cmake

**Comment by pendenaor** [comment] 2015-06-17 10:30
I'm a cmake noob, but maybe you could look at http://www.cmake.org/Wiki/BuildingWinDLL

**Comment by KjellKod** [comment] 2015-06-17 10:36
@pendenaor, what CMake arguments did you used to generate the solutions file?

**Comment by KjellKod** [comment] 2015-06-17 11:14
I have verified with cmake and the latest on g3log that the g3logger_shared.dll is generated

To reproduce I followed the instructions in the g3log/CMakeLists.txt
(in g3log)
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 12" ..
This will generate the solutions file g3log.sln

To build from command line:
msbuild g3log.sln /p:Configuration=Release

which generates 
in the Release directory
g3logger_shared.dll among other files.

**Comment by pendenaor** [comment] 2015-06-17 12:06
"g3logger_shared.dll" is generated, no problem with that, but not his import library "g3logger_shared.lib" which export functions or classes. This behavior is specific to the windows platform and vc compiler (gcc make it public by default).

**Comment by KjellKod** [comment] 2015-06-17 12:14
Aha. Thanks for the clarification.

**Comment by KjellKod** [comment] 2015-06-19 03:36
I agree that this should be fixed. I'm off on vacation for close to two weeks so I likely won't have time to look at this until after.

Pull requests are always welcomed ;)

**Comment by KjellKod** [comment] 2015-07-09 01:45
I have thought long and hard about this one. I'm OK with this being implemented but I will not do it myself. This one I will leave for someone on the Windows side to implement and do a pull request for it.

I'm less on the Windows side than on OSX and Linux side and a feature like this is better made by someone who has a good working knowledge of the ins and outs of DLLs.

**Comment by ctapmex** [comment] 2015-08-29 13:10
to realize this in the beginning you need to alter the structure in the same classes. 
LogWorkerImpl, LogCapture and some other

**Comment by jkhoogland** [comment] 2015-09-03 14:28
there is some logic coming up in cmake 3.4, 
that should make the generation of dlls on windows much easier:

http://www.kitware.com/blog/home/post/939

it might be worth waiting for cmake 3.4 to come out...

**Comment by KjellKod** [comment] 2015-09-03 22:27
Thanks

*Contact Information*
*Kjell Hedström*
*Mobile:  +1 - 617.378.1915*

*E-mail: Hedstrom@KjellKod.cc*

**Comment by cstamatopoulos** [comment] 2015-11-25 22:17
With cmake 3.4 it is possible to generate a definition file (.def) which is then used to create the import library. Just need to add in the cmake

    if(ADD_BUILD_WIN_SHARED OR NOT(MSVC OR MINGW))
     IF(MSVC)
       set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)
     ENDIF(MSVC)
     ....

However, without spending much time into it when the program terminates there are memory leaks.
I assume that this is probably the destruction of global objects. There is a bit of info on how to handle static and static const members over at 

http://www.kitware.com/blog/home/post/939

**Comment by KjellKod** [comment] 2015-11-28 21:49
@pendenaor can you please have a look at pull request https://github.com/KjellKod/g3log/pull/65

**Comment by pendenaor** [comment] 2015-12-01 08:27
I will try it on VC2015, i don't have VC2013 anymore.
I spent some times reading on inner limitations of windows dll, and, maybe, it's not a good idea to make g3log a shared lib !

**Comment by pendenaor** [comment] 2015-12-01 10:32
Ok, compiling fine with VC2015 and CMake 3.4.0, dll and import lib are correctly generated : All symbols are made public.
Good Work :+1:

**Comment by KjellKod** [comment] 2015-12-01 12:34
Great then it works both with 2013 and 2015

**Comment by KjellKod** [comment] 2015-12-01 12:34
I'm closing this once the PR is merged

**Comment by KjellKod** [comment] 2015-12-01 12:52
Closed since pull request https://github.com/KjellKod/g3log/pull/65 is merged

**Closed by KjellKod** 2015-12-01 12:52 UTC
Labels: enhancement, help wanted
