### ISSUE TITLE
Add ability to log thread id and/or name

### ISSUE THREAD

**Issue by bmagistro** [KjellKod/g3log#245] opened 2018-01-25 19:40 UTC
This may overlap with #218.
If a custom format string was available for messages regardless of sink, a user could change the layout of the log message or include additional information in every log message such as the threadid (`std::this_thread::get_id()`) or thread name (`pthread_setname_np()`).  I can see not supporting the name as it is likely not portable.

**Comment by KjellKod** [comment] 2018-01-26 00:00
Yup. This is a duplicate of https://github.com/KjellKod/g3log/issues/218

Please be aware that if you need this you can do one of: 
1. address https://github.com/KjellKod/g3log/issues/218
2. copy the default sink but do your own custom changes to it. It is easy to create a custom sink in g3log and it is pretty good documentation and test examples around it.

**Closed by KjellKod** 2018-01-26 00:00 UTC
